// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfbynmjvaifpiwjmlgto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mYnlubWp2YWlmcGl3am1sZ3RvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MDg3MjQsImV4cCI6MjA2NjA4NDcyNH0.WtOgk7fWz1xSB30LtebeT4f1UikQwty-ZgHPYolacUU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);